### ISSUE TITLE
LSTM for text summarization help

### ISSUE THREAD

**Issue by blaisewang** [abdullahfde/Twiiter_sentiment#1]
Hi Abdullah,

Sorry for contacting you in this way. I Googled your name but I cannot find your email address. In [this repo](https://github.com/DeepsMoseli/Bidirectiona-LSTM-for-text-summarization-), you commented that the code is wrong and do not use it. Do you find a better solution for this task later?

Best,
Blaise

**Comment by abdullahfde** [comment]
Hello, 
In fact I developed my own cod, but for now I can't share because I submitted a paper for publication   still under-processing . But this code was very useful for me, and it is working 
https://github.com/Tony607/Summarizing_Text_Amazon_Reviews/blob/master/summarize_reviews.ipynb

**Comment by blaisewang** [comment]
Great, thanks. I will look into it.
